spring.application.name=order-service

server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/order_service_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}

app.rabbitmq.email-exchange=${EMAIL_EXCHANGE:email.exchange}
app.rabbitmq.email-queue=${EMAIL_QUEUE:email.queue}
app.rabbitmq.email-routing-key=${EMAIL_ROUTING_KEY:email.confirmation}

server.forward-headers-strategy=framework

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:9000/auth/jwks}